AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Language Translator Lambda Function

Resources:
  TranslatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - TranslateFullAccess
        - ComprehendFullAccess
      Events:
        TranslatorAPI:
          Type: Api
          Properties:
            Path: /translate
            Method: post
